language:
  - clojure
  - javascript
cache:
  directories:
    - $HOME/.m2
    - node_modules
addons:
  chrome: stable
install:
  - npm install
  - npm install -g karma-cli
script:
  - lein eastwood
  - lein test
  - lein doo chrome-headless once
