sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.m2
    - node_modules
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
install:
  - npm install
  - npm install -g karma-cli
script:
  - lein eastwood
  - lein test
  - lein doo chrome-headless once

