sudo: required
dist: trusty
language: clojure
cache:
  directories:
    - $HOME/.m2
    - node_modules
addons:
  chrome: stable
install:
  - npm install
  - npm install -g karma-cli
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - lein eastwood
  - lein test
  - lein doo chrome once
